# Generated by Django 4.1 on 2023-06-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_creted_at_remove_todo_iscompleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='isCompleted',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
        migrations.AddField(
            model_name='todo',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
