# Generated by Django 4.1 on 2023-06-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_todo_iscompleted_alter_todo_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='iscompleted',
            new_name='isCompleted',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
